### ISSUE TITLE
希望能提供更多周边能力

### ISSUE THREAD

**Issue by zh1314** [zhangfisher/voerka-i18n#1]
1、历史项目改造：支持脚本或插件一键替换代码中的中文 t(‘中文’)
2、eslint插件支持：如存在中文未国际化则报错不让提交
3、支持翻译资源文件从服务端获取

@zhangfisher

**Comment by zhangfisher** [comment]
不好意思，麻烦详细说明一下

**Comment by zh1314** [comment]
1、历史项目改造
对于历史老项目 可以提供一种方式 可以对代码中所有的中文进行批量替换 用t函数包起来 这样不需要手动去代码里一个个找中文包裹t函数
2、eslint插件支持
如代码中存在中文未被t函数包裹 eslint时给出对应的报错或提示 当染可以通过 /* eslint-ignore-t */ 类似这样的方式绕过 代表不需要国际化
3、当前国际化翻译语言是放在前端项目代码里的，是否可以支持api服务端获取，将翻译资源文件放到服务端

**Comment by zhangfisher** [comment]
1、历史项目改造
对代码中所有的中文进行批量替换 用t函数包起来，这可是一个难题，容易误伤一大片，正则表达式匹配?代码，注释，拼接字符串，这些都难于做到可靠。
倒是可以考虑将用户的其他多语言的方案进行自动迁移靠谱点
比如vue-i18n，一键迁移到voerkai18n
因为，这些多语言方案一般都有较明确的特征，做自动化容易点。
2、eslint插件支持
这容易添堵吧
3、当前国际化翻译语言是放在前端项目代码里的，是否可以支持api服务端获取，将翻译资源文件放到服务端
这个主意不错，可以考虑！
