### ISSUE TITLE
执行extract，没有任何扫描和提取

### ISSUE THREAD

**Issue by cuiyueshuai** [zhangfisher/voerka-i18n#10]
node 环境：v16.14.0
React项目（非create-react-app创建，自定义webpack搭建项目）：版本17.0.2
未使用TS，默认所有的文件名都是jsx或者js，以及less进行样式控制
所有默认的源码路径位于：根目录  ./src 目录下，但是html模板文件位于根目录 ./public下 ，无其他异常配置

当前执行 init操作后，会自动在src目录下生成language文件夹，但是，执行extract命令没有任何作用，没有扫描和提取到任何中文字条，这是怎么回事呢？
项目结构如下：
[图片]
<img width="304" alt="d917fd10615d69f758ad47a3294744a" src="https://user-images.githubusercontent.com/13741688/223379496-8ef45d12-53c0-446e-8d7e-cf7d44a3d626.png">

**Comment by zhangfisher** [comment]
`extract`命令本质上是采用正则表达式从源文件中提取如`t("xxxxxx")`形式的文本，所以你的文件中需要将等待翻译的内容使用`t`包裹起来。

`extract`命令并不是提取中文

**Comment by cuiyueshuai** [comment]
那这样就尴尬了，修改的点就多了，中文地方，好吧，我觉得中文提取更好呀，不然我源代码里面t()的文本替换太多了呀

**Comment by cuiyueshuai** [comment]
结合你的方案，感觉建议，可以多做一个命令，要把源代码中所有中文形式的文本，原地替换成t("xxxxxx")形式文本，这样既符合你的方案，也让用户更好用啊，不然老项目突然要做国际化，去查看修改早期源码中文字符，工作量太大。

**Comment by zhangfisher** [comment]
并不是简单地替换成`t("xxxxx")`就行的，会有一系列的问题，无法进行判断哪些是需要翻译，并不简单地替换中文就行的，容易误伤一大片。

就算实现原地替换，大概率是执行后，面临一大堆的错误要处理。
