### ISSUE TITLE
请问vue2能使用吗

### ISSUE THREAD

**Issue by lty1601** [zhangfisher/voerka-i18n#11]
我在vue2项目中使用，voerkai18n extract 无法提取中文字段
![image](https://user-images.githubusercontent.com/50611995/227470411-7f248892-14e8-4beb-9d1f-8444ba297ff2.png)

**Comment by lty1601** [comment]
您好，咱这个在node15以下好像还是使用不了。我本地用的是node 14.20.0，然后在安装 @voerkai18n/cli 以及查看 @voerkai18n/cli 时会有报错。
![image](https://user-images.githubusercontent.com/50611995/227831123-1ecc0f04-e2a5-48b6-85bf-9f720ea654b7.png)

在项目中使用时，提取中文还是提取不了。
![1679886169689](https://user-images.githubusercontent.com/50611995/227831259-1de6cbb3-8e9e-4cb6-a63d-29e2ebdc7546.jpg)

**Comment by zhangfisher** [comment]
所依赖的`logsets`升级后有个bug，马上修复，请稍等

**Comment by zhangfisher** [comment]
最新的@voerkai18/cli 1.0.67解决了此问题，请尝试

**Comment by lty1601** [comment]
nice，可以提取了！

使用过程中遇到有个问题，Vue2 里全局注入报错。
![image](https://user-images.githubusercontent.com/50611995/228197796-6a5d685b-3260-4099-b88c-5ff7312c936d.png)

可能是因为全局注入不了，然后获取配置实例的时候取不到值
![image](https://user-images.githubusercontent.com/50611995/228199396-8fcec286-0d2b-4625-93c8-648fe241cb53.png)

**Comment by zhangfisher** [comment]
`@voerkai18n/vue`是针对`Vue3`的插件，如果要在vue2下使用

1- 不需要任何插件，`import {t} from "languages"`导入`t`函数并确保能执行即可，如果要切换语言则从`import { i18nScope } from "languages"`，调用`i18nScope.change`方法即可。

2.  如果有要用得更方便，可以自己写一个简单插件，大概如下:

```javascript
import { t,i18nScope } from "languages  // 从你本地的'languages'中导入
VoerkaI18nPlugin.install = function (Vue, options) {
 
  Vue.prototype.t= function (methodOptions) {
       return t(...arguments)
  }
  Vue.prototype.changeLanguage=function(lng){
      i18nScope.change(lng)
}
}
// 安装该插件后，就可以直接在组件中使用
vue.use(VoerkaI18nPlugin)


```
