### ISSUE TITLE
关于Babel插件

### ISSUE THREAD

**Issue by wangdaodao** [zhangfisher/voerka-i18n#13]
你好，按照开发示例在`babel.config.js`中这么配置：
```
const i18nPlugin =  require("@voerkai18n/babel")
module.expors = {
    plugins: [
        [
            i18nPlugin,
            {
                // 可选，指定语言文件存放的目录，即保存编译后的语言文件的文件夹
                // 可以指定相对路径，也可以指定绝对路径
                // location:"",
                autoImport:"#/languages"  
            }            
        ]
    ]
}
```
提示
![图片](https://user-images.githubusercontent.com/2317442/229048147-feb570a6-c5ea-4751-8ac8-16f5bddc5805.png)
请问这种情况是我这里的autoImport配置错了吗？这里配置了路径也不行。

另外手动引入 `t` 也报错，demo是基于vue2做的。

方便邮件或者微信沟通吗？群二维码已经过期了。

**Comment by zhangfisher** [comment]
一般为了方便项目导入，避免各种深度的相对导入，会为项目根配置一个特殊字符，如`@`或`~`
这种配置如果在`webpack`里面一般需要配置的，如下：

- **前提：需要能识别以`#`开头的路径**

```
// webpack.config.js
{
   resolve:{
     alias:{
         "#":path.join(__dirname,"src")       
     }
   }
}
```
这样再配置了`autoImport:"#/languages" `后，才可以有效识别以`#`开头的路径
如果你使用的是其他构建工具，如`vite`，方法也类似。

- **配置`autiImport`参数**

配置`autoImport:"#/languages" `的作用就是在每一个使用了`t`的源码文件中自动注入:
```
import { t } from "#/languages"  
```
而注入该语句的前提就是构建工具能识别。

- 你上面的错误可能是没有配置
- 例子中使用`#`仅是示例，实际项目中可能会使用`~`来指向源码根文件夹


- 使用`babel-plugin-module-resolver`,也可以配置别名，
- 
参考[这里](https://zhangfisher.github.io/voerka-i18n/guide/tools/babel)


- 有问题提`issus`，我会及时响应的
-

**Comment by wangdaodao** [comment]
写了一个最小复现的例子：https://github.com/wangdaodao/voerkai18n-demo

`vue.config.js`中也配置了`alias`。

https://github.com/wangdaodao/voerkai18n-demo/blob/master/vue.config.js#L8

另外运行的时候`languages/index.js`中

```js
const activeFormatters = defaultFormatters
```
这里没有使用`activeFormatters`，初始化项目后，会报错。

另外运行后，会报：

```
Uncaught TypeError: VoerkaI18nScope is not a constructor
```

![图片](https://user-images.githubusercontent.com/2317442/229391876-0e5e6d29-4927-4eb3-86f5-b0f95e0465de.png)

**Comment by zhangfisher** [comment]
`VoerkaI18n`没有在`Vue2`测试过，您知道的，现在除了历史项目外，一般不用`Vue2`，这样由于环境语法上的问题，可能会造成一些麻烦。

`@VoerkaI18n/runtime`正在使用`typescript`进行重构，在新版本出来前，您可以通过以下方法简单修改一下即可：


1. 使用`voerkaii18n compile -m esm`生成`esm`格式的源码(`languages`)，
2. 修改`languages/index.ts`文件，

```typescript

// 去除一下这行
const activeFormatters = defaultFormatters


// 在最后修改
// 删除
- export {
-     scopedTranslate as t,
-     scope as i18nScope
- }

// 添加
+ export const t = scopedTranslate
+ export const i18nScope = scope 


```

3. 在`main.js` 注册一下简单的`Vue`插件

```
import { t,i18nScope } from "./languages" 
Vue.use({
    install(Vue) {
        Vue.prototype.t =t
        Vue.prototype.i18n= i18nScope 
    }
})
```
然后就可以

-  在模板中使用`t`函数进行翻译了
- 调用`this.i18n.change()`切换语言，当然注意，切换后要重新渲染

感谢您的反馈！

**Comment by zhangfisher** [comment]
补充一下：

- 如果只在`vue`文件中使用，则没有必要使用`babel`，使用`vue2`插件更方便
- 仅在`js`文件中使用时为了避免重复导入`t`函数才有必要使用`babel`插件。
