### ISSUE TITLE
不支持tsx 吗

### ISSUE THREAD

**Issue by XuChaow** [zhangfisher/voerka-i18n#15]
![image](https://github.com/zhangfisher/voerka-i18n/assets/29518526/accb6ffb-0fe2-4465-8daf-158db5b7332c)

**Comment by zhangfisher** [comment]
默认值不包括`.tsx`

你可以在提取时传入`voerkai18n extract --filetypes  js,vue,html,jsx,ts,tsx,mjs,cjs

在`2.0.9`版本会将`tsx`设为默认

**Comment by zhangfisher** [comment]
`2.0.9`版本已发布
