### ISSUE TITLE
是不是不支持umi，在umi当中导入会报错

### ISSUE THREAD

**Issue by please1988** [zhangfisher/voerka-i18n#16]
![image](https://github.com/zhangfisher/voerka-i18n/assets/81510458/9703b1aa-b8d2-41ae-8a24-9452b13dbe7a)

**Comment by zhangfisher** [comment]
没问题的，umi也是标准的React应用，出现这个问题可能跟你的环境有关，可以试试安装一下react

我使用最新版本的`umi`建了一个应用，可以正常运行.
![umi_i18n](https://github.com/zhangfisher/voerka-i18n/assets/2050579/ce9e5f37-2dae-4951-8d2d-aeb131c2a167)
