### ISSUE TITLE
提取到很多不匹配的内容

### ISSUE THREAD

**Issue by zengqin20** [zhangfisher/voerka-i18n#17]
![image](https://github.com/zhangfisher/voerka-i18n/assets/65145124/7f92ddd8-ba52-4ecf-98ee-e61c8da6dcc1)
![image](https://github.com/zhangfisher/voerka-i18n/assets/65145124/589aa186-0a01-4d91-ab9f-b5a12c078fd7)

vue2项目中提取jsx文件，许多不被t("")包裹的字符串都被提取到了default.json中

**Comment by zhangfisher** [comment]
麻烦提供样本数据以便我进行改进，谢谢
提供一个可复制文本，谢谢

**Comment by zengqin20** [comment]
> 麻烦提供样本数据以便我进行改进，谢谢 提供一个可复制文本，谢谢

麻烦给我个邮箱，我发给你

**Comment by zhangfisher** [comment]
wxzhang@126.com
