### ISSUE TITLE
报错提示 默认语言包必须是静态内容,不能使用异步加载的方式.

### ISSUE THREAD

**Issue by XM1313** [zhangfisher/voerka-i18n#18]
使用环境 vite + vue3
![image](https://github.com/zhangfisher/voerka-i18n/assets/111414255/6700e0ba-11d0-4fa3-94e4-e29bb65f85ca)
![image](https://github.com/zhangfisher/voerka-i18n/assets/111414255/b9b78e50-7597-496d-b945-66aafc6bd293)
![image](https://github.com/zhangfisher/voerka-i18n/assets/111414255/a417d240-9b54-42e8-aa89-e1c71c420eb6)

**Comment by zhangfisher** [comment]
是否没有执行`voerkai18n compile`?

**Comment by XM1313** [comment]
> 请贴上`languages/index.ts`
> 
> 是否没有执行`voerkai18n compile`?
执行了，是否因为不是ts版本的？使用ts版本无此问题

**Comment by zhangfisher** [comment]
如果使用`js`，则生成的是`languages/index.js`

我确认一下

**Comment by XM1313** [comment]
有没有群加一下，这里等不到消息 @zhangfisher

**Comment by zhangfisher** [comment]
网站上有微信二维码

**Comment by XM1313** [comment]
官网看得好难 这个是不是官网的？
![image](https://github.com/zhangfisher/voerka-i18n/assets/111414255/c6f59f02-ab02-4101-a659-fe4e00afffb6)

**Comment by zhangfisher** [comment]
按个浏览器，明显是缺少了一些样式没有下载完成

**Comment by XM1313** [comment]
三种常见的浏览器都加载不出来 实在不行贴出二维码加你吧

**Comment by zhangfisher** [comment]
网站没有问题，由于是在`Github Pages`上，所以可能不同地区会有些访问问题，你懂的。

![image](https://github.com/zhangfisher/voerka-i18n/assets/2050579/14517c34-f7f7-40dc-9603-fac311f47062)
