### ISSUE TITLE
tarojs + vue3 微信小程序报错

### ISSUE THREAD

**Issue by 455631680** [zhangfisher/voerka-i18n#20]
![Snipaste_2023-10-12_18-20-04](https://github.com/zhangfisher/voerka-i18n/assets/7570630/cc16b695-c526-4952-b32e-9dc060a672e5)

**Comment by 455631680** [comment]
![image](https://github.com/zhangfisher/voerka-i18n/assets/7570630/1bb16b5e-6187-4a2d-b85c-7c12e0ffa771)

**Comment by zhangfisher** [comment]
`@voerkai18n/runtime`提供了两种构建产物`commonjs`和`esm`，同时`languages`下生成的文件也支持`ts`、`commonjs`和`esm`三种形式的源码编译产物。

你这种情况可能跟所用的编译环境对`commonjs`和`esm`等的处理兼容性有关，你可以试着分别采用`voerkai18n compile`来生成`commonjs`或`esm`或`ts`

详见[这里](https://zhangfisher.github.io/voerka-i18n/#/zh/guide/tools/cli?id=%e7%bc%96%e8%af%91-compile)
