### ISSUE TITLE
【bug】voerkai18n compile 执行后 会注入错误语法导致编译错误

### ISSUE THREAD

**Issue by itmanyong** [zhangfisher/voerka-i18n#23]
1.执行以下命令之后
```bash
voerkai18n init
voerkai18n extract
voerkai18n compile
```
2.查看文件`languages/index.js`，顶部导入语句中`activeFormatters`和`activeMessages`导入错误，如下
![image](https://github.com/zhangfisher/voerka-i18n/assets/53500371/c3299652-0279-4c3b-8d54-dab7f53b65a6)

**Comment by zhangfisher** [comment]
确认这是一个BUG ，可以先手工修改一下

const activeFormatters = defaultFormatters
const activeMessages = defaultMessages

将在2.0.28中修复此错误

**Comment by zhangfisher** [comment]
已经在2.0.28中修复此错误
