### ISSUE TITLE
点击事件设置后不切换语言。

### ISSUE THREAD

**Issue by 2213601279** [zhangfisher/voerka-i18n#25]
![image](https://github.com/zhangfisher/voerka-i18n/assets/45991092/d84b4b9a-94bf-4b22-b603-ebf8745e80e6)
切换语言后没有切换中英文

**Comment by 2213601279** [comment]
代码如下vue3 
        <template #dropdown>
          <el-dropdown-menu @command="selected = $event" style="width: 138px">
            <el-dropdown-item command="中文" @click="changeToZh">中文</el-dropdown-item>
            <el-dropdown-item command="English" @click="changeToEn">English</el-dropdown-item>
          </el-dropdown-menu>
        </template>
js部分:
async function changeToZh() {
  console.log("change to zh", i18n.languages);
  console.log("默认语言", i18n.defaultLanguage);
  console.log("当前语言", i18n.activeLanguage);
  console.log("当前语言 =====", i18n.languages[0].name);
  i18n.activeLanguage = i18n.languages[0].name;
  // await i18nScope.change("zh");
}
async function changeToEn() {
  console.log("change to english", i18n.languages);
  console.log("默认语言", i18n.defaultLanguage);
  console.log("当前语言", i18n.activeLanguage);
  i18n.activeLanguage = "en";
  // await i18nScope.change("en");
}

**Comment by zhangfisher** [comment]
[这里](https://github.com/zhangfisher/voerka-i18n/tree/master/examples/vue3-ts)有个vue3的例子，可以看一下
