### ISSUE TITLE
没有忽略注释

### ISSUE THREAD

**Issue by yck-rgb** [zhangfisher/voerka-i18n#28]
我这样写注释// const aaa=t("扫码")
然后执行voerkai18n extract后，这段注释文字也被提取了

**Comment by zhangfisher** [comment]
这段代码的上下文是在Vue文件，还是？

**Comment by yck-rgb** [comment]
在main.js里



------------------------------------------------------------------
***@***.***>
日　期：2024年01月05日 22:13:20
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [zhangfisher/voerka-i18n] 没有忽略注释 (Issue #28)

这段代码的上下文是在Vue文件，还是？
