### ISSUE TITLE
voerkai18n init报错

### ISSUE THREAD

**Issue by zh1314** [zhangfisher/voerka-i18n#3]
![image](https://user-images.githubusercontent.com/13436139/181442580-62331c6c-7eed-41a2-b090-5c3590273d4d.png)

**Comment by zhangfisher** [comment]
请提供环境说明，好分析问题

另外，也可以：
- 跳过初始化操作，直接使用extract
- 手动创建languages文件夹和languages/settings.json，具体内容查看文档

**Comment by zh1314** [comment]
mac环境 node版本v12.22.12 
extract也是报错

**Comment by cjahv** [comment]
@zhangfisher 需要在bin文件第一行加上`#!/usr/bin/env node` wsl/linux/mac等系统需要使用Shebang指明使用什么程序执行脚本 https://github.com/zhangfisher/voerka-i18n/blob/395ff3899cc8345941ca1cd8534815f577449774/packages/cli/index.js#L1
