### ISSUE TITLE
uniapp voerkai18n init 报错解决

### ISSUE THREAD

**Issue by jhs1873** [zhangfisher/voerka-i18n#30]
根目录有package.json的前提,没有就npm ini 初始化一个
```js
node:internal/errors:478
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
```
解决办法:根目录新建目录src

**Comment by zhangfisher** [comment]
这里是uniapp的例子

https://github.com/zhangfisher/voerka-i18n/tree/master/examples/uniapp-vue3

**Comment by jhs1873** [comment]
> 这里是uniapp的例子
> 
> https://github.com/zhangfisher/voerka-i18n/tree/master/examples/uniapp-vue3

感谢,我用的是uniapp的vue2老项目 @zhangfisher
