### ISSUE TITLE
vue3 .ts 文件提取成功，但未翻译

### ISSUE THREAD

**Issue by cencenyue** [zhangfisher/voerka-i18n#31]
vue 文件中引用了 constant.ts ，如 export const test = t("需要翻译的文字")
vue 文件中：
import test from constant.ts

提取的翻译文件中包含 "需要翻译的文字":{zh:"需要翻译的文字",en:"Text that needs translation"}
但是 test 的文本内容不跟随激活语言的变化而变化，一直都是 "需要翻译的文字"

**Comment by zhangfisher** [comment]
这是因为test这个常量只初始化了一次，所以当然一直是原始文本
得这样改一下才行。
```
// constant.ts
export const test =()=> t("需要翻译的文字")

import { test } from "constant.ts"

test()   
```

 常量是一个函数，这样才能保证每次读取时均能得到执行
