### ISSUE TITLE
自定翻译覆盖了已经翻译过的内容

### ISSUE THREAD

**Issue by cencenyue** [zhangfisher/voerka-i18n#32]
对于已经翻译了的复数，再次执行自动翻译，会覆盖以前的内容

原内容如：
"周{}": {
    "zh": ["0", "周一", "周二", "周三", "周四", "周五", "周六", "周日"],
    "en": ["0", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    "$files": []
  },
自动翻译：voerkai18n translate  --mode auto
翻译之后：
 "周{}": {
    "zh": ["0", "周一", "周二", "周三", "周四", "周五", "周六", "周日"],
    "en": "Zhou {}",
    "$files": []
  },
已经翻译的英文数组被覆盖了

**Comment by cencenyue** [comment]
请问自动翻译自动跳过的策略是什么，怎么样可以规避一下

**Comment by zhangfisher** [comment]
这是自动翻译对复数场景考虑不周导致的

新发布`2.1.3`解决此问题

现在会略过复数，需要手动对复数进行翻译。
