### ISSUE TITLE
Vue3 的 setup 模式下，在父组件中切换语言，如果子组件引入了 t 方法，子组件无法切换语言。

### ISSUE THREAD

**Issue by cheng0532** [zhangfisher/voerka-i18n#36]
<img width="1107" alt="企业微信20240402-140822@2x" src="https://github.com/zhangfisher/voerka-i18n/assets/16147857/13a3d94d-4bbe-4e2d-9a94-bc6fd9a367af">
<img width="1137" alt="企业微信20240402-140923@2x" src="https://github.com/zhangfisher/voerka-i18n/assets/16147857/dd6b4434-3131-464c-8845-8d31400d4620">

**Comment by zhangfisher** [comment]
`@voerkai18n/vue`插件注入了一个`t`函数，支持响应式，在模板里面可以直接使用。
如果在`script`里面使用`import { t } from "@/languages"`导入的是普通的`t`函数，没有响应式处理所以不能使用。

如果你在`script`里面要使用换一个别名
或者自己写一个`use`

**Comment by cheng0532** [comment]
> `@voerkai18n/vue`插件注入了一个`t`函数，支持响应式，在模板里面可以直接使用。 如果在`script`里面使用`import { t } from "@/languages"`导入的是普通的`t`函数，没有响应式处理所以不能使用。
> 
> 如果你在`script`里面要使用换一个别名 或者自己写一个`use`

好的，谢谢

**Comment by Mrliurock** [comment]
> > `@voerkai18n/vue`插件注入了一个`t`函数，支持响应式，在模板里面可以直接使用。 如果在`script`里面使用`import { t } from "@/languages"`导入的是普通的`t`函数，没有响应式处理所以不能使用。
> > 如果你在`script`里面要使用换一个别名 或者自己写一个`use`
> 
> 好的，谢谢

script 中怎样使用具有响应式的t函数呢
