### ISSUE TITLE
Vue3 @voerkai18n/vite 自动 t 函数导入无效

### ISSUE THREAD

**Issue by liganghui** [zhangfisher/voerka-i18n#37]
按照文档说明  增加并配置了@voerkai18n/vite插件  , 但是在vue3代码中 如果脚本是下列格式 

```js
<script setup>
console.log(t("Welcome to VoerkaI18n"))
</script>
```
会提示错误 
```
ReferenceError: t is not defined 
```
@voerkai18n/vite插件的作用不是自动引入t函数么 , 还是需要每次调用手动引入 ?

我使用的依赖版本 : 
```
 "vue": "^3.4.21",
 "vite": "^5.1.6",
 "@vitejs/plugin-vue": "^5.0.4",
  "@voerkai18n/runtime": "^2.1.9",
  "@voerkai18n/vite": "^2.1.9",
  "@voerkai18n/vue": "^2.1.9",
```
[最小化Demo.zip](https://github.com/zhangfisher/voerka-i18n/files/14836981/Demo.zip)

**Comment by zhangfisher** [comment]
https://zhangfisher.github.io/voerka-i18n/#/zh/guide/tools/vite?id=%e8%87%aa%e5%8a%a8%e5%af%bc%e5%85%a5t%e5%87%bd%e6%95%b0

默认不自动导入，需要配置`autoImport`参数

**Comment by liganghui** [comment]
感谢 眼拙
