### ISSUE TITLE
请问可以支持 VSCODE 的 i18n Ally吗

### ISSUE THREAD

**Issue by eachann1024** [zhangfisher/voerka-i18n#40]
RT

**Comment by eachann1024** [comment]
先 star

**Comment by zhangfisher** [comment]
`i18n Ally`是一个非常棒的多语言辅助插件。

`VoerkaI18n`的设计理念与其他多语言方案一个显著的不同就是，不需要使用`key`。

在其他多语言方案中一般是通过，指定`key`来查表的，如：

```ts
t('Layout configuration')
t("twoColumnsMenuBarColor")
t("twoIsColumnsMenuBarColorGradual")
t("twoIsColumnsMenuHoverPreload")
t("threeTitle")
t("threeIsCollapse")
```

这导致一个问题，不符合直觉，实际编码时不能直观地知道内容是什么，又时要取一个有意义的`key`也是让人头疼的。

因此，`i18n Ally`的核心功能就是让我们可以类型提示，也可以进行实时反向显示，就是因为不直观，才需要`i18n Ally`插件的帮助。

而`VoerkaI18n`则抛弃了这种设计机制，直接在代码中使用`t("布局")`这种翻译机制，再通过一系列工具链完成自动化工作，所以是不需要`i18n Ally`来做辅助的。
