### ISSUE TITLE
能修复下文档样式吗？

### ISSUE THREAD

**Issue by xxxace** [zhangfisher/voerka-i18n#41]
能修复下文档样式吗？ 阅读体验很不友好，麻烦你了

**Comment by xxxace** [comment]
![image](https://github.com/zhangfisher/voerka-i18n/assets/60084325/6b7e427d-2555-4c93-91e8-fb1dd17fa839)

**Comment by zhangfisher** [comment]
这是网络问题导致的，有一些文件没有成功下载，

网站用到了一`https://fastly.jsdelivr.net`的一些CDN资源，可能你所在的网络访问有问题，可以你多刷新一下。

或者查一下如何访问
