### ISSUE TITLE
1

### ISSUE THREAD

**Issue by yhl-186** [zhangfisher/voerka-i18n#42]
![屏幕截图 2024-07-06 163620](https://github.com/zhangfisher/voerka-i18n/assets/56154079/2e3a971b-f60c-4d3a-8ce2-c8f75743fc5c)
想问一下这种问题是啥原因

**Comment by zhangfisher** [comment]
可能是你模板有问题，Vue? React?

**Comment by yhl-186** [comment]
已经解决了，但还是有点鸡肋，就是在提取文本的时候用这个:label=t("XXXX")，但运行必须要改成:label=“t(‘XXXX‘)”。如果提取文本用:label=“t(‘XXXX‘)”，在default.json文件里面会出现“t(‘XXXX‘)”这个问题。用的vue2
