### ISSUE TITLE
app.__instance.update()在生产环境下会出错，建议移除

### ISSUE THREAD

**Issue by xinsuihexu** [zhangfisher/voerka-i18n#5]
<img width="814" alt="image" src="https://user-images.githubusercontent.com/44325577/212613087-16a6916d-b3a7-40a6-a449-25eeee43fe34.png">

**Comment by zhangfisher** [comment]
经验证，的确`app_instance.update`在生产环境下无法使用，因此将重新设计在`vue`下的重新渲染问题

**Comment by zhangfisher** [comment]
新版本已经发布，重构`@voerkai18n/vue`，请查阅文档
