### ISSUE TITLE
是否支持 IE10+？

### ISSUE THREAD

**Issue by aniude** [zhangfisher/voerka-i18n#53]
试了一下直接 babel, runtime 部分生成的 index.mjs 依赖的 flex-tools 不会再被编译。IE10 打开会报错。看编译后的代码是否解决方案？

**Comment by aniude** [comment]
看了一下 flex-tools 代码里面用了 Proxy 对象，似乎不太可能对 IE10 进行兼容了。

**Comment by zhangfisher** [comment]
应该是不支持的

**Comment by aniude** [comment]
我看了一下，似乎用到  Proxy 的 https://github.com/search?q=repo%3Azhangfisher%2Fflex-tools%20new%20Proxy%20&type=code 几个库，似乎 voerka-i18n 均未使用到。

看样子似乎是voerka-i18n打包的时候强制依赖把其他不相关的库都引入进来了。

**Comment by aniude** [comment]
@zhangfisher  感觉应该还有机会可以兼容IE10+

**Comment by zhangfisher** [comment]
理论上应该可以通过编译兼容的
问题是现在不太需要考虑了，甚至电脑上都找不到IE10了
有兴趣可以自己fork改改就行

**Comment by aniude** [comment]
我看了一下似乎是 tsup.config.js  noExternal:['flex-tools'] 把整个 flex-tools 都加载进来了。按理改成按需加载就可以了

**Comment by aniude** [comment]
https://github.com/zhangfisher/flex-tools/pull/2

**Comment by aniude** [comment]
目前能发现似乎都是 flex-tools 正则表达式兼容的问题。 剩下的问题 babel 都可以解决。不过这里我也尝试用了 babel / corejs 的 polyfill， 似乎都不生效。

**Comment by zhangfisher** [comment]
建议fork一个分支

- 构建是使用tsup，https://tsup.egoist.dev/#es5-support
- 将构建目标降级到es5，然后再视情况配置需要的polyfill

**Comment by aniude** [comment]
麻烦 release 一下新的 npm version.我用 IE 再测试一下能不能过

**Comment by aniude** [comment]
本地 跑 pnpm: build:all
```
@voerkai18n/runtime:build: src/scope.ts(2,10): error TS2305: Module '"flex-tools/*"' has no exported member 'isFunction'.
@voerkai18n/runtime:build: 
@voerkai18n/runtime:build: src/formatter.ts(15,10): error TS2305: Module '"flex-tools/*"' has no exported member 'isFunction'.
@voerkai18n/runtime:build: 
@voerkai18n/runtime:build: src/translate.ts(3,10): error TS2305: Module '"flex-tools/*"' has no exported member 'isFunction'.
@voerkai18n/runtime:build: 
@voerkai18n/runtime:build:  ELIFECYCLE  Command failed with exit code 1.
```

不确定是不是已知问题

**Comment by zhangfisher** [comment]
flex-tools有一个导出错误，已经修复
