### ISSUE TITLE
发布的npm包换行符有误

### ISSUE THREAD

**Issue by cjahv** [zhangfisher/voerka-i18n#7]
# 问题说明

命令执行演示
```
❯ voerkai18n extract
/usr/bin/env: “node\r”: 没有那个文件或目录
```

查看`node_modules/@voerkai18n/cli/index.js`文件是crlf换行符

# 原因分析

linux系统中`Shebang`会读取执行文件第一行，`crlf`的换行符会在行末多出一个`\r`字符，导致查找执行文件从`node`变为了查找`node\r`，从报错提示中也能证明这一点

# 建议

将cli文件的换行符改为lf

# 影响

开发影响：因为crlf换行符是windows格式，如果改为lf可能需要同时修改git配置 https://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf

运行影响：nodejs脚本本身能够支持crlf和lf格式，在windows上执行js脚本，是先调用bat或ps1载入node程序后，再执行js脚本，过程中没有换行符影响

**Comment by zhangfisher** [comment]
原则上是不需要添加/usr/bin/env: node，因为在安装时如果指定了package.json中的bin字段，nodejs会自动在全局的目录中生成对应的脚本，这个是平台无关的，不存在还需要nodejs脚本中添加/usr/bin/env: node这样的

也就是说，真正的脚本是nodejs生成的，如果存在问题，是否跟nodejs版本有关系？
是否查看一下本机npm全局目录中生成的voerki18n脚本，贴上来看看

**Comment by cjahv** [comment]
这是众所周知的，软件运行与平台息息相关，导致该问题的原因可以参考 https://zh.wikipedia.org/zh-hans/Shebang

当然除此之外还可以使用更长的命令执行：node ./node_modules/voerka-i18n/cli/index.js init

使用命令`voerkai18n init`代替`node ./node_modules/voerka-i18n/cli/index.js init`可提高工作效率

**Comment by zhangfisher** [comment]
新发布`@voerkai18n/cli`-->`1.061`，将换行符更改为`lf`
