### ISSUE TITLE
执行voerkai18n init命令时候出错，出错信息是validateString(arg, 'path'), the 'path' argument must be of type string, received null.

### ISSUE THREAD

**Issue by enforceway** [zhangfisher/voerka-i18n#74]
![image](https://github.com/user-attachments/assets/77a0f4ac-01a2-46e8-b71c-dd1901dab369)

Node: v20.12.2
@voerkai18n/cli: 2.1.13

**Comment by zhangfisher** [comment]
应该在具有package.json的文件夹下执行

**Comment by enforceway** [comment]
![image](https://github.com/user-attachments/assets/3dcd5d71-078d-4fbc-b0b1-aa034e912940)
你好感谢回复，我是按照文档提示操作的。现在是初始化i18n工程的步骤，出现的这个错误。
