### ISSUE TITLE
执行 extract命令，赶紧啥都没扫描出来，没有成功提取文本

### ISSUE THREAD

**Issue by cuiyueshuai** [zhangfisher/voerka-i18n#9]
node 环境：v16.14.0
React项目（非create-react-app创建，自定义webpack搭建项目）：版本17.0.2
未使用TS，默认所有的文件名都是jsx或者js，以及less进行样式控制
所有默认的源码路径位于：根目录  ./src 目录下，但是html模板文件位于根目录 ./public下 ，无其他异常配置

当前执行 init操作后，会自动在src目录下生成language文件夹，但是，执行extract命令没有任何作用，没有扫描和提取到任何中文字条，这是怎么回事呢？
项目结构如下：
[图片]

**Comment by zhangfisher** [comment]
`extract`命令本质上是通过正则表达式提供源码文件中的形如`t("xxxx")`的由`t`翻译函数包裹的内容。

所以你要确保你的源码中，所有需要翻译的内容均要使用加个`t("要翻译的内容")`
